INSERT INTO [dbo].[Questions] ([Question_ID], [Question], [Option]) VALUES (1, N'Do you want Color Touchscreen?', N'Yes-No')
INSERT INTO [dbo].[Questions] ([Question_ID], [Question], [Option]) VALUES (2, N'Do you want ECG?', N'Yes-No')
INSERT INTO [dbo].[Questions] ([Question_ID], [Question], [Option]) VALUES (3, N'Do you want Ambient light adjustments?', N'Yes-No')
INSERT INTO [dbo].[Questions] ([Question_ID], [Question], [Option]) VALUES (4, N'Do you want NBP measurement display?', N'Yes-No')
INSERT INTO [dbo].[Questions] ([Question_ID], [Question], [Option]) VALUES (5, N'Do you want SpO2?', N'Yes-No')
INSERT INTO [dbo].[Questions] ([Question_ID], [Question], [Option]) VALUES (6, N'Do you want Portable?', N'Yes-No')
