INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0001', N'IntelliVue Guardian Solution', N'Raghav Singhal')
INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0002', N'IntelliVue MX550', N'Varsha Jain')
INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0003', N'SureSigns VM1', N'Saudamini Khare')
INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0004', N'SureSigns VSi', N'Raghav Singhal')
INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0005', N'Efficia CM Series', N'Varsha Jain')
INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0006', N'Efficia CMS200', N'Saudamini Khare')
INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0007', N'Avalon CL', N'Raghav Singhal')
INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0008', N'Avalon FM40', N'Varsha Jain')
INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0009', N'SureSigns VS2+', N'Saudamini Khare')
INSERT INTO [dbo].[Monitors] ([Model], [Name], [Sales_Incharge]) VALUES (N'M_0010', N'IntelliVue MP90', N'Raghav Singhal')