//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBotDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMonitor
    {
        public string Model { get; set; }
        public string Feature_ID { get; set; }
    }
}
